### 先都加载到cpu上

In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "5,1,2"
os.environ["TOKENIZERS_PARALLELISM"] = "False"
from modeling_mixtral import MixtralForCausalLM
from transformers import AutoTokenizer
import torch
import torch.nn as nn
from typing import Optional
import json
### HQQ量化
from hqq.core.quantize import *
from hqq.models.hf.mixtral import MixtralPatch
import transformers
from hqq.models.base import BaseHQQModel
from accelerate import init_empty_weights
import gemlite
from gemlite import GemLiteLinearTriton 
GemLiteLinearTriton.get_default_gemv = lambda *args, **kwargs: 'GEMV'

class BaseHQQHFModel(BaseHQQModel):
    # Save model architecture
    @classmethod
    def cache_model(cls, model, save_dir):
        model.config.save_pretrained(save_dir)

    # Create empty model from config
    @classmethod
    def create_model(cls, save_dir, kwargs):
        model_kwargs = {}
        for key in ["attn_implementation"]:
            if key in kwargs:
                model_kwargs[key] = kwargs[key]

        config = transformers.AutoConfig.from_pretrained(
            cls.get_config_file(save_dir)
        )

        with init_empty_weights():
            model = MixtralForCausalLM._from_config(config, **model_kwargs)

        return model

class MixtralHQQ(MixtralPatch, BaseHQQHFModel):
    pass

with open('../path.json', 'r') as f:
    path = json.load(f)
    model_name = path['mixtral']
    threshold_path = path['chess_up_threshold']

save_dir = './hqqsaved'
dtype = torch.float16
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.pad_token_id = tokenizer.eos_token_id
### 从保存的权重中加载
llm = MixtralHQQ.from_quantized(save_dir, compute_dtype=dtype, device='cpu')
HQQLinear.set_backend(HQQBackend.PYTORCH)

backend       = "gemlite" #'torchao_int4' #"torchao_int4" (4-bit only) or "gemlite" (4-bit + 2-bit)
# #Optimize
from hqq.utils.patching import prepare_for_inference
prepare_for_inference(llm, backend=backend, verbose=True)

if(backend == 'gemlite'):
	gemlite.core.GEMLITE_TRITON_RESTRICT_M = True
	gemlite.core.GemLiteLinear.load_config('/tmp/gemlite_config.json')

/home/lz/miniconda3/envs/hqq/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


using atten... sdpa


/data2/lz/hqq-master/hqq/models/base.py:251: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(cls.get_weight_file(save_dir), map_location=map_location)


In [2]:
device_map = {layer_idx: 'cuda:1' if layer_idx <= 16 else 'cuda:2' for layer_idx in range(1, 32)}
from convert import convert_mixtral_to_cached_mlp

prefill_layers = 6  ### 固定在device上的MLP层数
llm, cached_mlps = convert_mixtral_to_cached_mlp(llm, dtype, sparsity=0.8, backends=backend, 
                                                 device='cuda:0', device_map=device_map, threshold_path = threshold_path, prefill_layers=prefill_layers)

device_id = 0

/data2/lz/On-the-Fly_MoE_Inference/offloading/convert.py:160: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  up_th = torch.load(threshold_path, map_location='cuda')["up_proj_

Thresholds loaded from /data2/lz/On-the-Fly_MoE_Inference/saving/threshold/c4_mixtral_up/thresholds_0_8.pt
active neural num  2867
active neural num  2867
... loading layer 6 for pipelineLLM
... loading layer 7 for pipelineLLM
... loading layer 8 for pipelineLLM
... loading layer 9 for pipelineLLM
... loading layer 10 for pipelineLLM
... loading layer 11 for pipelineLLM
... loading layer 12 for pipelineLLM
... loading layer 13 for pipelineLLM
... loading layer 14 for pipelineLLM
... loading layer 15 for pipelineLLM
... loading layer 16 for pipelineLLM
... loading layer 17 for pipelineLLM
... loading layer 18 for pipelineLLM
... loading layer 19 for pipelineLLM
... loading layer 20 for pipelineLLM
... loading layer 21 for pipelineLLM
... loading layer 22 for pipelineLLM
... loading layer 23 for pipelineLLM
... loading layer 24 for pipelineLLM
... loading layer 25 for pipelineLLM
... loading layer 26 for pipelineLLM
... loading layer 27 for pipelineLLM
... loading layer 28 for pipelineLL

/data2/lz/On-the-Fly_MoE_Inference/offloading/pipelinellm.py:17: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.load_state_dict(torch.load(f'../expert_predictor/training

In [ ]:
from pipelinellm import PipelineLLM
# 创建流水线模型
PLLM = PipelineLLM(llm, cached_mlps, 1, 3, training_epoch=20,
                   device='cuda:0', device_map=device_map, prefill_layers=prefill_layers, print_layer_info=True) ### use ep

In [3]:
class CUDAGraphRunner():
    def __init__(self, model):
        self.model = model
        self.cuda_graph = None
        self.graph_input = torch.zeros((1,4096), dtype=torch.float16, device=f'cuda:{device_id}')
        self.graph_output = None
    
    def capture(self, x,):
        assert self.cuda_graph is None
        self.graph_input = self.graph_input.copy_(x).to(x.device)
        self.cuda_graph = torch.cuda.CUDAGraph()
        # self.cuda_graph.enable_debug_mode()
        with torch.cuda.graph(self.cuda_graph):
            self.graph_output = self.model(self.graph_input,)
        torch.cuda.synchronize()
        
    def forward(self, x,):
        self.graph_input.copy_(x)
        self.cuda_graph.replay()
        return self.graph_output

    def __call__(self, *args, **kwargs):
        return self.forward(*args, **kwargs)
    
inp = torch.randn(1, 4096).half().cuda(device_id)
graphs = [[None for _ in range(8)] for _ in range(prefill_layers)]
# expert=llm.model.layers[0].block_sparse_moe.experts[1]
# print(expert(inp))
# graph_runner = CUDAGraphRunner(expert)
# graph_runner.capture(inp)
# graphs[0][1]=graph_runner
# print(graphs[0][1](inp))
for i in range(prefill_layers):
    for j in range(8):
        expert=llm.model.layers[i].block_sparse_moe.experts[j]
        print(expert(inp))
        graph_runner = CUDAGraphRunner(expert)
        graph_runner.capture(inp)
        graphs[i][j]=graph_runner
        print(graphs[i][j](inp))

tensor([[ 0.7646, -0.2427,  0.2208,  ...,  0.5122,  0.3179, -0.2690]],
       device='cuda:0', dtype=torch.float16)
tensor([[ 0.7651, -0.2432,  0.2219,  ...,  0.5132,  0.3186, -0.2698]],
       device='cuda:0', dtype=torch.float16)
tensor([[-0.4468,  0.2944,  0.5732,  ...,  0.7163, -0.2991,  0.4709]],
       device='cuda:0', dtype=torch.float16)
tensor([[-0.4451,  0.2954,  0.5718,  ...,  0.7173, -0.2983,  0.4714]],
       device='cuda:0', dtype=torch.float16)
tensor([[ 0.3928, -0.1058, -0.3047,  ..., -0.3560,  0.7578, -0.2568]],
       device='cuda:0', dtype=torch.float16)
tensor([[ 0.3928, -0.1052, -0.3044,  ..., -0.3567,  0.7588, -0.2529]],
       device='cuda:0', dtype=torch.float16)
tensor([[ 0.2124,  0.4792,  0.1733,  ..., -0.4539,  0.1676,  0.5039]],
       device='cuda:0', dtype=torch.float16)
tensor([[ 0.2140,  0.4805,  0.1744,  ..., -0.4539,  0.1653,  0.5039]],
       device='cuda:0', dtype=torch.float16)
tensor([[ 0.2910,  0.6528,  0.2764,  ...,  0.5068, -0.4456, -0.4441]],
 

In [4]:
for i in range(0, prefill_layers):
    for j in range(len(llm.model.layers[0].block_sparse_moe.experts)):
        llm.model.layers[i].block_sparse_moe.experts[j].graph = graphs[i][j]
        # graphs[i][j]
    # torch.compile(llm.model.layers[i].block_sparse_moe.forward, fullgraph=False, mode='max-autotune-no-cudagraphs')
        # graphs[i][j]
        # torch.compile(llm.model.layers[i].block_sparse_moe.experts[j].kernel_forward, fullgraph=True, mode='max-autotune-no-cudagraphs')
        # llm.model.layers[i].block_sparse_moe.experts[j].kernel_forward
        # \torch.compile(llm.model.layers[i].block_sparse_moe.experts[j].kernel_forward, fullgraph=True, mode="reduce-overhead")


In [34]:
x = torch.rand((1,4096), device='cuda:0', dtype=torch.float16)
print("None:", llm.model.layers[0].block_sparse_moe.experts[1](x))
llm.model.layers[0].block_sparse_moe.experts[1].graph = graphs[0][1]
print("cuda:graph", llm.model.layers[0].block_sparse_moe.experts[1](x))

### 测试时间开销

In [6]:
import json
# import torch._dynamo.config
from datasets import load_dataset, Dataset
from transformers import GenerationConfig

input_length = 2
MAX_LENGTH = 2
output_length = 10
test_samples = 1

with open("../path.json", "r") as f:
    paths = json.load(f)
    fineweb_path = paths["fineweb"]

def preprocess_data(data, tokenizer):
	# 使用 tokenizer 将文本数据转换为模型输入
	inputs = tokenizer(data, padding="max_length", truncation=True, max_length=MAX_LENGTH, return_tensors="pt")
	inputs["labels"] = inputs.input_ids.clone()
	return inputs

filt_type = fineweb_path.split('.')[-1]
fineweb = load_dataset(filt_type, data_files=fineweb_path) #726000
fineweb_text = fineweb['train']['text']

print("warm up ...")
# 预热（避免第一次运行时的额外开销）
for text in fineweb_text[:5]:
    inputs = preprocess_data(text, tokenizer)
    with torch.no_grad():
        output = llm(input_ids=inputs["input_ids"].cuda(device_id), attention_mask=inputs["attention_mask"].cuda(device_id))

warm up ...
in prefill layer  0
in prefill layer  1
in prefill layer  2
in prefill layer  3
in prefill layer  4
in prefill layer  5
in prefill layer  6
in prefill layer  7
in prefill layer  8
in prefill layer  9
in prefill layer  10
in prefill layer  11
in prefill layer  12
in prefill layer  13
in prefill layer  14
in prefill layer  15
in prefill layer  16
in prefill layer  17
in prefill layer  18
in prefill layer  19
in prefill layer  20
in prefill layer  21
in prefill layer  22
in prefill layer  23
in prefill layer  24
in prefill layer  25
in prefill layer  26
in prefill layer  27
in prefill layer  28
in prefill layer  29
in prefill layer  30
in prefill layer  31
in prefill layer  0
in prefill layer  1
in prefill layer  2
in prefill layer  3
in prefill layer  4
in prefill layer  5
in prefill layer  6
in prefill layer  7
in prefill layer  8
in prefill layer  9
in prefill layer  10
in prefill layer  11
in prefill layer  12
in prefill layer  13
in prefill layer  14
in prefill layer  15


In [7]:
from transformers import GenerationConfig
import torch

# 定义 input_length 和 output_length 的范围
# input_length_range = [16]
# output_length_range = [128,256]
input_length_range = [16,32]  # 16到32
output_length_range = [128,256,512,1024]  # 128到1024

test_samples = 5
device_id = 0

def preprocess_data(data, tokenizer, max_length):
    # 使用 tokenizer 将文本数据转换为模型输入
    inputs = tokenizer(data, padding="max_length", truncation=True, max_length=max_length, return_tensors="pt")
    inputs["labels"] = inputs.input_ids.clone()
    return inputs

for input_length in input_length_range:
    for output_length in output_length_range:
        MAX_LENGTH = input_length
        generated_all = 0
        prefill_time, decode_time = 0, 0
        reloaded_experts = 0

        # 打开文件以写入结果
        with open(f"{input_length}-{output_length}.out", "w") as f:
            print(f"output length is {output_length}", file=f)
            for text in fineweb_text[2:2+test_samples]:
                inputs = preprocess_data(text, tokenizer, MAX_LENGTH)
                ### 清空统计数据
                PLLM.get_prefill_time()
                PLLM.get_reload_experts()

                # 测试时间
                start_event = torch.cuda.Event(enable_timing=True)
                end_event = torch.cuda.Event(enable_timing=True)

                # 开始计时
                torch.cuda.synchronize()
                start_event.record()

                # 前向传播
                with torch.no_grad():
                    output = llm.generate(
                        input_ids=inputs["input_ids"].cuda(device_id),
                        attention_mask=inputs["attention_mask"].cuda(device_id),
                        max_length=input_length + output_length,  # 总长度为输入长度 + 输出长度
                        generation_config=GenerationConfig(do_sample=False),
                        pad_token_id=tokenizer.pad_token_id, 
                        # cache_implementation="static" ## moe not support
                    )

                # 结束计时
                end_event.record()
                torch.cuda.synchronize()

                # 计算时间
                elapsed_time = start_event.elapsed_time(end_event) / 1000  # 转换为秒
                decode_time += elapsed_time
                cur_prefill_time = PLLM.get_prefill_time()
                prefill_time += cur_prefill_time
                print(f"Generated length: {len(output[0]) - input_length}", f"Time taken: {elapsed_time:.2f} s,", f"prefill time: {cur_prefill_time:.2f} s", file=f)
                # print(output, file=f)
                print(tokenizer.batch_decode(output, skip_special_tokens=True), file=f)

                generated_all += (len(output[0]) - input_length - 1)
                reloaded_experts += PLLM.get_reload_experts()

            print("Generate speed:", '{:.4f}'.format((generated_all+test_samples) / decode_time) , 'token/s', file=f)
            timepertoken = (decode_time - prefill_time) / (generated_all)
            print("decode phase speed(not cover prefill phase):", '{:.4f}'.format(1/timepertoken) , 'token/s', file=f)
            expertpertoken = reloaded_experts / generated_all
            print("the number of reloaded experts per token:", '{:.3f}, ({:.2f}%)'.format(expertpertoken, 100 * expertpertoken / ((32-prefill_layers) * 2)), file=f)

in prefill layer  0
in prefill layer  1
in prefill layer  2
in prefill layer  3
in prefill layer  4
in prefill layer  5
in prefill layer  6
in prefill layer  7
in prefill layer  8
in prefill layer  9
in prefill layer  10
in prefill layer  11
in prefill layer  12
in prefill layer  13
in prefill layer  14
in prefill layer  15
in prefill layer  16
in prefill layer  17
in prefill layer  18
in prefill layer  19
in prefill layer  20
in prefill layer  21
in prefill layer  22
in prefill layer  23
in prefill layer  24
in prefill layer  25
in prefill layer  26
in prefill layer  27
in prefill layer  28
in prefill layer  29
in prefill layer  30
in prefill layer  31
in prefill layer  0
in prefill layer  1
in prefill layer  2
in prefill layer  3
in prefill layer  4
in prefill layer  5
in prefill layer  6
in prefill layer  7
in prefill layer  8
in prefill layer  9
in prefill layer  10
in prefill layer  11
in prefill layer  12
in prefill layer  13
in prefill layer  14
in prefill layer  15
in prefill l

In [4]:
import json
from datasets import load_dataset, Dataset
from transformers import GenerationConfig

input_length = 10
MAX_LENGTH = input_length
output_length = 256
test_samples = 5
device_id = 0

def preprocess_data(data, tokenizer):
	# 使用 tokenizer 将文本数据转换为模型输入
	inputs = tokenizer(data, padding="max_length", truncation=True, max_length=MAX_LENGTH, return_tensors="pt")
	inputs["labels"] = inputs.input_ids.clone()
	return inputs

generated_all = 0
prefill_time, decode_time = 0, 0
reloaded_experts = 0
print("output length is {}".format(output_length))
for text in fineweb_text[2:2+test_samples] :
    inputs = preprocess_data(text, tokenizer)
    ### 清空统计数据
    PLLM.get_prefill_time()
    PLLM.get_reload_experts()

    # 测试时间
    start_event = torch.cuda.Event(enable_timing=True)
    end_event = torch.cuda.Event(enable_timing=True)

    # 开始计时
    torch.cuda.synchronize()
    start_event.record()

    # 前向传播
    with torch.no_grad():
        output = llm.generate(
            input_ids=inputs["input_ids"].cuda(device_id),
            attention_mask=inputs["attention_mask"].cuda(device_id),
            max_length=input_length + output_length,  # 总长度为输入长度 + 输出长度
            generation_config=GenerationConfig(do_sample=False),
            pad_token_id=tokenizer.pad_token_id, 
            # cache_implementation="static" ## moe not support
        )

    # 结束计时
    end_event.record()
    torch.cuda.synchronize()

    # 计算时间
    elapsed_time = start_event.elapsed_time(end_event) / 1000  # 转换为秒
    decode_time += elapsed_time
    cur_prefill_time = PLLM.get_prefill_time()
    prefill_time += cur_prefill_time
    print(f"Generated length: {len(output[0]) - input_length}", f"Time taken: {elapsed_time:.2f} s,", f"prefill time: {cur_prefill_time:.2f} s")
    # print(output)
    print(tokenizer.batch_decode(output, skip_special_tokens=True))

    generated_all += (len(output[0]) - input_length - 1)
    reloaded_experts += PLLM.get_reload_experts()

print("Generate speed:", '{:.4f}'.format((generated_all+test_samples) / decode_time) , 'token/s')
timepertoken = (decode_time - prefill_time) / (generated_all)
print("decode phase speed(not cover prefill phase):", '{:.4f}'.format(1/timepertoken) , 'token/s')
expertpertoken = reloaded_experts / generated_all
print("the number of reloaded experts per token:", '{:.3f}, ({:.2f}%)'.format(expertpertoken, 100 * expertpertoken / ((32-prefill_layers) * 2)))

output length is 256
in prefill layer  0
in prefill layer  1
in prefill layer  2
in prefill layer  3
in prefill layer  4
in prefill layer  5
in prefill layer  6
in prefill layer  7
in prefill layer  8
in prefill layer  9
in prefill layer  10
in prefill layer  11
in prefill layer  12
in prefill layer  13
in prefill layer  14
in prefill layer  15
in prefill layer  16
in prefill layer  17
in prefill layer  18
in prefill layer  19
in prefill layer  20
in prefill layer  21
in prefill layer  22
in prefill layer  23
in prefill layer  24
in prefill layer  25
in prefill layer  26
in prefill layer  27
in prefill layer  28
in prefill layer  29
in prefill layer  30
in prefill layer  31
Generated length: 256 Time taken: 57.54 s, prefill time: 17.62 s
['Helpful Hints on the Iodine Patch Test\n\nThe iodine patch test is a simple, inexpensive, and effective way to test for food allergies. It is also a great way to test for food allergies in children.\n\nThe iodine patch test is a simple, inexpensive, 

In [6]:

########################################################################
#Save gemlite cache
if(backend == 'gemlite'):
	gemlite.core.GemLiteLinear.cache_config('/tmp/gemlite_config.json') 

#### torch.profile

attention使用sdpa实现

In [8]:
import json
from datasets import load_dataset, Dataset
from transformers import GenerationConfig

input_length = 1
MAX_LENGTH = input_length
output_length = 2
test_samples = 4

with open("../path.json", "r") as f:
    paths = json.load(f)
    fineweb_path = paths["fineweb"]

def preprocess_data(data, tokenizer):
	# 使用 tokenizer 将文本数据转换为模型输入
	inputs = tokenizer(data, padding="max_length", truncation=True, max_length=MAX_LENGTH, return_tensors="pt")
	inputs["labels"] = inputs.input_ids.clone()
	return inputs

filt_type = fineweb_path.split('.')[-1]
fineweb = load_dataset(filt_type, data_files=fineweb_path) #726000
fineweb_text = fineweb['train']['text'][:test_samples] 

print("output length is {}".format(output_length))
text = fineweb_text[0]
inputs = preprocess_data(text, tokenizer)

# cached_mlp.clear_load_from_cpu_stats()
with torch.profiler.profile(
    activities=[
        torch.profiler.ProfilerActivity.CPU,
        torch.profiler.ProfilerActivity.CUDA,
    ]
) as p:
    # 前向传播
    with torch.no_grad():
        output = llm.generate(
            input_ids=inputs["input_ids"].cuda(),
            attention_mask=inputs["attention_mask"].cuda(),
            max_length=input_length + output_length,  # 总长度为输入长度 + 输出长度
            generation_config=GenerationConfig(do_sample=False),
            pad_token_id=tokenizer.eos_token_id
        )
print(p.key_averages().table(
    sort_by="self_cpu_time_total", row_limit=-1))
p.export_chrome_trace("./offloading-3090-graph.json")

output length is 2
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg    # of Calls  
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
                                       cudaLaunchKernel        17.36%      43.880ms        17.36%      43.880ms       9.768us       0.000us         0.00%       0.000us       0.000us          4492  
gemlite::gemv_revsplitK_A16fWnO16f_int32packing_forw...        12.80%      32.351ms        15.41%      38.957ms     374.591us       4.254ms         6.68%       4.387ms      42.185us       

#### 测试一个正常输出

In [5]:
import json
from datasets import load_dataset, Dataset
from transformers import GenerationConfig

input_length = 10
MAX_LENGTH = input_length
output_length = 16
test_samples = 1

def preprocess_data(data, tokenizer):
	# 使用 tokenizer 将文本数据转换为模型输入
	inputs = tokenizer(data, padding="max_length", truncation=True, max_length=MAX_LENGTH, return_tensors="pt")
	inputs["labels"] = inputs.input_ids.clone()
	return inputs

generated_all, decode_time, prefill_time = 0, 0, 0
# print("max output length is {}".format(output_length))
text = "The future of AI is here, "

clear_prefill_time = PLLM.get_prefill_time()
clear_experts = PLLM.get_reload_experts()
# print("need to zero: ", clear_experts, clear_prefill_time)

llm.eval()
inputs = preprocess_data(text, tokenizer)
# 测试时间
start_event = torch.cuda.Event(enable_timing=True)
end_event = torch.cuda.Event(enable_timing=True)

# 开始计时
torch.cuda.synchronize()
start_event.record()

# 前向传播
with torch.no_grad():
    output = llm.generate(
        input_ids=inputs["input_ids"].cuda(device_id),
        attention_mask=inputs["attention_mask"].cuda(device_id),
        max_length=input_length + output_length,  # 总长度为输入长度 + 输出长度
        generation_config=GenerationConfig(do_sample=False),
        pad_token_id=tokenizer.pad_token_id, 
        # cache_implementation="static" ## moe not support
    )

# 结束计时
end_event.record()
torch.cuda.synchronize()

# 计算时间
elapsed_time = start_event.elapsed_time(end_event) / 1000  # 转换为秒
decode_time += elapsed_time
cur_prefill_time = PLLM.get_prefill_time()
prefill_time += cur_prefill_time
print(f"Generated length: {len(output[0]) - input_length}", f"Time taken: {elapsed_time:.2f} s", f"prefill time: {cur_prefill_time:.2f} s")
# print(output)
print(tokenizer.batch_decode(output, skip_special_tokens=True))

generated_all += (len(output[0]) - input_length -1)

timepertoken = (decode_time - prefill_time) / (generated_all)
print("decode phase speed:", '{:.4f}'.format(1/timepertoken) , ' token/s')
print("the number of experts reload per token:", PLLM.get_reload_experts() / generated_all)

in prefill layer  0
in prefill layer  1
in prefill layer  2
in prefill layer  3
in prefill layer  4
in prefill layer  5
in prefill layer  6
in prefill layer  7
in prefill layer  8
in prefill layer  9
in prefill layer  10
in prefill layer  11
in prefill layer  12
in prefill layer  13
in prefill layer  14
in prefill layer  15
in prefill layer  16
in prefill layer  17
in prefill layer  18
in prefill layer  19
in prefill layer  20
in prefill layer  21
in prefill layer  22
in prefill layer  23
in prefill layer  24
in prefill layer  25
in prefill layer  26
in prefill layer  27
in prefill layer  28
in prefill layer  29
in prefill layer  30
in prefill layer  31
Generated length: 16 Time taken: 20.76 s prefill time: 17.74 s
['The future of AI is here,  and it’s called ChatGPT.\n\nChatGPT is a']
decode phase speed: 4.9713  token/s
the number of experts reload per token: 5.266666666666667


### 加载到GPU上

In [1]:
from transformers import MixtralForCausalLM, AutoTokenizer
import torch
import torch.nn as nn
from typing import Optional
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1,2"
import json

def get_model(model_name, device_map, dtype=torch.bfloat16):
    llm = MixtralForCausalLM.from_pretrained(
        model_name,
        device_map=device_map,
        use_cache=True,
        torch_dtype=dtype,
    ) 
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.pad_token_id = tokenizer.eos_token_id

    return llm, tokenizer

with open('../path.json', 'r') as f:
    path = json.load(f)
    model_name = path['mixtral']
    # threshold_path = path[threshold_path_name]

with open('../quantize/device_map_1.json', 'r') as f:
    device_map = json.load(f)

dtype = torch.float16
llm, tokenizer = get_model(model_name, device_map, dtype=dtype)

/home/bcds/.conda/envs/llm/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading checkpoint shards: 100%|██████████| 19/19 [00:25<00:00,  1.36s/it]
